### ISSUE TITLE
请问当字幕长度过短，比如只有几个字，可否实现滚动？

### ISSUE THREAD

**Issue by SpringFestivalcake** [AnyLifeZLB/ScrollTextView#14]

**Comment by SpringFestivalcake** [comment]
不好意思，没表述清除，我的意思是，文字很短 ，能否实现横向滚动

**Comment by AnyLifeZLB** [comment]
第一版本是可以的，目前没有支持。我想知道什么情况需要能完全显示的情况下仍要滚动？
G 友们的意见是不要滚动😊

**Comment by coffee330501** [comment]
现在的版本短字幕还是不能滚动吗

**Comment by AnyLifeZLB** [comment]
好吧，我让他滚动起来😊

**Comment by kiwiw** [comment]
辛苦楼主，我也有这个需求

**Comment by JustinChiang123** [comment]
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
notice += (str + "　　　　　　　　");
解决你们的问题，仔细想想是不是很巧妙。

**Comment by AnyLifeZLB** [comment]
@SpringFestivalcake @coffee330501 @kiwiw @JustinChiang123  1.4.7版本可以了。看看是否OK了！

**Comment by kiwiw** [comment]
1.4.8可以了，但是楼主能否更新下文档，辛苦
