### ISSUE TITLE
如何再XML和java代码中设置文字的居中显示（How to set text's gravity in XML and java code?）

### ISSUE THREAD

**Issue by coffee330501** [AnyLifeZLB/ScrollTextView#15]

**Comment by AnyLifeZLB** [comment]
没太懂你的描述，或者直接描述你要的效果吧

**Comment by coffee330501** [comment]
这是因为之前字幕太短不滚动时靠左对齐了，我就退而求其次想让他居中，结果发现居中不了。------------------ 原始邮件 ------------------
发件人: "Felix"<notifications@github.com>
发送时间: 2019年12月18日(星期三) 下午3:12
收件人: "AnyLifeZLB/ScrollTextView"<ScrollTextView@noreply.github.com>;
抄送: "coffee330501"<1034440274@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AnyLifeZLB/ScrollTextView] 如何再XML和java代码中设置文字的居中显示（How to set text's gravity in XML and java code?） (#15)



没太懂你的描述，或者直接描述你要的效果吧
 
&mdash;

**Comment by coffee330501** [comment]
谢谢啦，现在我是拼接空字符的方法让他滚动的，适应不同屏幕很麻烦。------------------ 原始邮件 ------------------
发件人: "Felix"<notifications@github.com>
发送时间: 2019年12月18日(星期三) 下午3:12
收件人: "AnyLifeZLB/ScrollTextView"<ScrollTextView@noreply.github.com>;
抄送: "coffee330501"<1034440274@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AnyLifeZLB/ScrollTextView] 如何再XML和java代码中设置文字的居中显示（How to set text's gravity in XML and java code?） (#15)



没太懂你的描述，或者直接描述你要的效果吧
 
&mdash;

**Comment by coffee330501** [comment]
请问这个滚动字幕是真的无限循环吗，我开了一晚上它就不动了。------------------ 原始邮件 ------------------
发件人: "Felix"<notifications@github.com>
发送时间: 2019年12月18日(星期三) 下午3:12
收件人: "AnyLifeZLB/ScrollTextView"<ScrollTextView@noreply.github.com>;
抄送: "coffee330501"<1034440274@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AnyLifeZLB/ScrollTextView] 如何再XML和java代码中设置文字的居中显示（How to set text's gravity in XML and java code?） (#15)



没太懂你的描述，或者直接描述你要的效果吧
 
&mdash;

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue

**Comment by AnyLifeZLB** [comment]
短字幕现在也可以滚动了，你可以设置滚动的次数也可以让他一直滚动。已经发新版了
没问题可以close issue
