### ISSUE TITLE
残影

### ISSUE THREAD

**Issue by JustinChiang123** [AnyLifeZLB/ScrollTextView#16]
activity 来回切换，并且上下滑动页面，残影很明显 清不掉。   版本1.4.6  所有机型都有

**Comment by getglory** [comment]
SurfaceView是会有这个问题。我之前做视频播放就遇到，后来换成TextureView就好了。不知道这个库换成TextureView来实现能否解决。

**Comment by AnyLifeZLB** [comment]
@JustinChiang123 你的现象和这个一样吗？https://github.com/AnyLifeZLB/ScrollTextView/issues/8
