### ISSUE TITLE
一堆问题，不好用

### ISSUE THREAD

**Issue by RainUtopia** [AnyLifeZLB/ScrollTextView#18]
1、没有设置滚动列表类似setContent(List<String> content)方法，
2、文字大小设置没用，
3、没有start和stop方法
4、点击方法回调之类的也没有封装
。。。

不知道哪来的这么多star，呵呵

**Comment by AnyLifeZLB** [comment]
慢走不送啊

**Comment by AnyLifeZLB** [comment]
自己给自己点赞就有了。慢走不送啊
