### ISSUE TITLE
播放视频的时候滚动字幕会卡

### ISSUE THREAD

**Issue by maud597371516** [AnyLifeZLB/ScrollTextView#19]
需求：
       公司要求做一个电视广告系统，在播放视频的同时，需要在底部加一个滚动广告
问题：
       使用系统自带的Textview实现跑马灯效果没有出现这种卡顿的情况，但是Textview会有一个问题，就是运行的时候，内存会一直往上涨，而您的这个控件在内存上控制的很好很稳定。但是在使用videoview播放视频的时候，使用您的ScrollTextView播放文字会出现卡顿情况。不知道是不是因为运行内存太小的原因导致的。
硬件：
       系统 Android 4.4.4
       内存大小 512M
       磁盘大小 4G

**Comment by AnyLifeZLB** [comment]
13 年我做广告机的时候也用VideoView 和ScrollTextView ,没遇到过卡 ，你用命令看看系统CPU 和内存

也可以看看在一般配置的手机上面是否卡顿
