### ISSUE TITLE
setText首次不显示内容

### ISSUE THREAD

**Issue by AgoniAlways** [AnyLifeZLB/ScrollTextView#21]
设备：华为荣耀HLK-AL00
OS：Android 10
第二次打开页面出现内容并滚动

**Comment by AnyLifeZLB** [comment]
有没有LOG 信息， 可以的话帮忙断点看看什么问题

**Comment by AnyLifeZLB** [comment]
在测试云平台跑Demo 并没有出现此问题，有没有更多的信息
