### ISSUE TITLE
当字数过了1k字，开头就会出现文字堆叠现象

### ISSUE THREAD

**Issue by ydw2305** [AnyLifeZLB/ScrollTextView#24]
如果字符数量超过了1k个，如果是横向滚动，最左边会有个所有文字堆叠的小方块，大小为单个文字的宽高。可以通过缝隙看到文字在背后滚动。虽然可以通过位移把布局往左偏移一个字符，但是并不是最终解决方案。不知道作者有什么处理方式嘛？

**Comment by AnyLifeZLB** [comment]
1千个字啊，看来我忙完这段时间要好好处理一下Issues 了

**Comment by AnyLifeZLB** [comment]
@ydw2305 我用Demo 跑了一下，超过1K子也没有什么问题呀，你是跑的Demo 吗？机型信息提供一下

**Comment by ydw2305** [comment]
@AnyLifeZLB 是跑的demo，机型是平板或者模拟器。字号是32sp，无尽的。不止是千字，之前说错了，我是6个随机字符循环一千次。背景黑，字色白。我测试过了，是canvas.drawText()这个东西没法写那么多字。

**Comment by ydw2305** [comment]
我现在的处理办法是每20个字切成一份，然后计算字宽并依次移动绘制

**Comment by AnyLifeZLB** [comment]
贴代码
