### ISSUE TITLE
想请问多个一起滚动支持吗

### ISSUE THREAD

**Issue by Zhangxd77** [AnyLifeZLB/ScrollTextView#27]
我的使用场景是有多个，而且是有可能一起滚动，现在就是不动，而且上面文字也显示不出
还请指导我哪里问题，谢谢

**Comment by AnyLifeZLB** [comment]
支持的， 我没看到你的程序没法支持，Demo  XML 多放几个

**Comment by AnyLifeZLB** [comment]
<anylife.scrolltextview.ScrollTextView
        android:id="@+id/scrollText"
        android:layout_width="match_parent"
        android:layout_height="44dp"
        android:layout_marginTop="10dp"
        android:background="#99224433"
        android:singleLine="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        customAttr:clickEnable="true"
        customAttr:isHorizontal="true"
        customAttr:speed="4"
        customAttr:text="请点击「设置图标」设置相关属性"
        customAttr:text_color="@android:color/white"
        customAttr:text_size="22sp" />
