### ISSUE TITLE
在recyclerview  适配器布局使用显示不出来!!!!

### ISSUE THREAD

**Issue by yeStudents** [AnyLifeZLB/ScrollTextView#28]

**Comment by AnyLifeZLB** [comment]
每个Item 中 有一个滚动字幕 这样子吗？

**Comment by yeStudents** [comment]
> 每个Item 中 有一个滚动字幕 这样子吗？
是的

**Comment by AnyLifeZLB** [comment]
![image](https://user-images.githubusercontent.com/15169396/127296190-5adc7745-5086-4159-a8b9-232c0b6272a3.png)
![image](https://user-images.githubusercontent.com/15169396/127296220-ad9c8f63-564c-410a-b46c-8d48a4661ac0.png)


我这里尝试都可以显示，并且正常滚动呢

**Comment by AnyLifeZLB** [comment]
![image](https://user-images.githubusercontent.com/15169396/127296487-ffd4e51b-538e-4249-b45a-5830ffa08a92.png)
