### ISSUE TITLE
在水平滚动的时候文字不能垂直居中

### ISSUE THREAD

**Issue by wangsanpiao** [AnyLifeZLB/ScrollTextView#3]
在水平滚动的时候文字不能垂直居中

**Comment by AnyLifeZLB** [comment]
@wangsanpiao 什么手机？截屏我看看

**Comment by happyburglar** [comment]
@wangsanpiao 
draw方法有问题导致字体无法居中绘制，修改如下

/**
     * Draw text
     *
     * @param X X
     * @param Y Y
     */
    public synchronized void draw(float X, float Y) {
        Canvas canvas = surfaceHolder.lockCanvas();
        canvas.drawColor(Color.TRANSPARENT, Mode.CLEAR);

//        canvas.drawText(text, X, Y, paint);

        Rect bgRect = new Rect(0,0,viewWidth,viewHeight);

        //计算baseline
        Paint.FontMetrics fontMetrics=paint.getFontMetrics();
        float distance=(fontMetrics.bottom - fontMetrics.top)/2 - fontMetrics.bottom;
        float baseline=bgRect.centerY()+distance;
        canvas.drawText(text, X, baseline, paint);

        surfaceHolder.unlockCanvasAndPost(canvas);
    }

**Comment by crykid** [comment]
您好，使用您的控件时，在fragmentA中使用，切换fragmentB之后文字仍然可见并且还在滚动，切换fragmentC之后就不再显示了。

**Comment by AnyLifeZLB** [comment]
@happyburglar 感谢，已经更新 V1.4.2 @wangsanpiao
