### ISSUE TITLE
我这边测试时，文字内容设置过大时，字体边缘就有锯齿的情况了。

### ISSUE THREAD

**Issue by LyhAndroid** [AnyLifeZLB/ScrollTextView#31]

**Comment by LyhAndroid** [comment]
在构造器里加入这个就好多了
// 消除边缘锯齿
paint.setFlags(Paint.ANTI_ALIAS_FLAG);
paint.setAntiAlias(true);
paint.setFilterBitmap(true);

**Comment by AnyLifeZLB** [comment]
Gooooood ,安排加上了
