### ISSUE TITLE
使用这个控件，导致屏幕剧烈抖动。

### ISSUE THREAD

**Issue by supermanwu** [AnyLifeZLB/ScrollTextView#5]
我用的机器是Android4.4系统的定制机，不知道是什么原因，只要一用这个控件，屏幕就会剧烈抖动，我在网上查了下，好像是因为SurfaceView的双缓存机制导致的，我试着改了下，屏幕倒是不抖动了，但显示不对了~~，再说下，我的这机器如果输出分辨率是800*600和1280*768的时候都不会使屏幕抖动，只有再输出分辨率是1920*1080的时候屏幕就抖动，也许跟机器的硬件有关系，但是我也找不到原因，请问作者是否能软件上做一些修改？

**Comment by AnyLifeZLB** [comment]
你好，最早我就是在全志A20 方案的4.4 系统上面跑的，但是现在我没有硬件环境修改输入分辨率了。不能复现我也不好改，你要是邮寄硬件过来我可以尝试修改

**Comment by AnyLifeZLB** [comment]
今天更新到1.3 版本了

**Comment by FloraFang12345** [comment]
清明节用了2台手机在公司插上电跑了3天，早上来看很稳定，各种指标都正常。
准备在正式项目使用了

**Comment by AnyLifeZLB** [comment]
为更多信息，我关闭了
