### ISSUE TITLE
水平滚动，activity页面切换再回来多次 ,文字错乱 重叠问题

### ISSUE THREAD

**Issue by yi-qingqiu** [AnyLifeZLB/ScrollTextView#8]

**Comment by FloraFang12345** [comment]
奇怪，我怎么复线不了，能否截图看看 @yi-qingqiu

**Comment by AnyLifeZLB** [comment]
请提供系统版本，手机型号 等信息

**Comment by loveanao** [comment]
![BEFC06AB74915FE6FB1B554FD2E006BF](https://user-images.githubusercontent.com/11850710/58303895-ae515900-7e24-11e9-9be4-bacf3dbb2522.jpg)手机型号为 华为mate8 系统最新8.0 

在Fragemnt布局里面使用该控件，当底部TAB切换，通过隐藏和显示Fragment会出现这个问题。

滚动控件，应该在社区栏目下，但切换到订单时候，就是如图。

**Comment by AnyLifeZLB** [comment]
1.4.4 已经解决，更新一下看看 @loveanao

**Comment by JustinChiang123** [comment]
implementation 'anylife.scrolltextview:ScrollTextviewLib:1.4.6'   还是有这个问题

**Comment by AnyLifeZLB** [comment]
先 FragmentPagerAdapter + viewPager.setCurrentItem

**Comment by AnyLifeZLB** [comment]
建议使用 FragmentPagerAdapter+ViewPager ，如果一定要通过隐藏和显示 管理Fragment。我后期来适配
